use_frameworks!

platform :ios, '10.0'

target 'swc-navigator_Example' do
  pod 'swc-navigator', :path => '../'

  target 'swc-navigator_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
